const exercises = [
  {
    name: "Push-Ups",
    type: "Strength",
    target_muscle_group: "Chest",
    duration_in_seconds: 30,
    description: "A bodyweight exercise to strengthen the chest, shoulders, and triceps.",
    xp: 50,
  },
  {
    name: "Squats",
    type: "Strength",
    target_muscle_group: "Legs",
    duration_in_seconds: 40,
    description: "A lower body exercise that targets quads, hamstrings, and glutes.",
    xp: 60,
  },
  {
    name: "Plank",
    type: "Core",
    target_muscle_group: "Abs",
    duration_in_seconds: 60,
    description: "Hold your body in a straight line while supporting your weight on your forearms and toes.",
    xp: 70,
  },
  {
    name: "Jumping Jacks",
    type: "Cardio",
    target_muscle_group: "Full Body",
    duration_in_seconds: 45,
    description: "A cardio exercise to improve endurance and warm up the body.",
    xp: 40,
  },
  {
    name: "Bicep Curls",
    type: "Strength",
    target_muscle_group: "Arms",
    duration_in_seconds: 50,
    description: "An arm-focused exercise using dumbbells to target the biceps.",
    xp: 65,
  },
  {
    name: "Burpees",
    type: "Cardio",
    target_muscle_group: "Full Body",
    duration_in_seconds: 60,
    description: "A high-intensity full-body exercise for endurance and strength.",
    xp: 80,
  },
  {
    name: "Lunges",
    type: "Strength",
    target_muscle_group: "Legs",
    duration_in_seconds: 50,
    description: "A single-leg exercise to strengthen quads, hamstrings, and glutes.",
    xp: 70,
  },
  {
    name: "Mountain Climbers",
    type: "Cardio",
    target_muscle_group: "Core",
    duration_in_seconds: 40,
    description: "A cardio exercise that engages your core and improves agility.",
    xp: 60,
  },
  {
    name: "Tricep Dips",
    type: "Strength",
    target_muscle_group: "Arms",
    duration_in_seconds: 30,
    description: "An upper-body exercise focusing on the triceps using a bench or similar support.",
    xp: 55,
  },
];

module.exports = exercises
